language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - ~/.m2/repository

services:
  - docker

before_install:
  - docker build -t allansilva/kafka4dev:latest .
  - docker run -d -p 127.0.0.1:9092:9092 -p 127.0.0.1:2181:2181 allansilva/kafka4dev:latest

script: mvn test -B -f tests/pom.xml

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
