language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - ~/.m2/repository

services:
  - docker

before_install:
  - docker build -t allansilva/kafka4dev:1.0.2-scala.2.12 .
  - docker run -d -p 127.0.0.1:9092:9092 -p 127.0.0.1:2181:9092 allansilva/kafka4dev:1.0.2-scala.2.12

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -f tests/pom.xml

script: mvn test -B -f tests/pom.xml

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: 1.0.2-scala.2.12
